### PR TITLE
Calculating initial offset properly, using better matrix

### PR DESCRIPTION
**Pull request by tkell**

### CODE REVIEW

**Comment by tkell** [comment]
Sign error when calculating initial offset in stereo.

Replaced `csr_matrix` with `lil_matrix` to get rid of the warning, too.

**Comment by bmcfee** [comment]
Ok, my original bad test case works now, but this one fails:
```
→  python reverse.py  ~/data/CAL500/mp3/art_tatum-willow_weep_for_me.mp3 
Traceback (most recent call last):
  File "reverse.py", line 19, in <module>
    out = synthesize(beats)
  File "/home/bmcfee/git/amen/amen/synthesize.py", line 64, in synthesize
    resampled_audio, left_offsets, right_offsets = time_slice.get_samples()
  File "/home/bmcfee/git/amen/amen/time.py", line 32, in get_samples
    left_offsets, right_offsets = self._get_offsets(starting_sample, ending_sample)
  File "/home/bmcfee/git/amen/amen/time.py", line 46, in _get_offsets
    zero_crossings = librosa.zero_crossings(channel)
  File "/home/bmcfee/git/librosa/librosa/core/audio.py", line 526, in zero_crossings
    y[np.abs(y) <= threshold] = 0
TypeError: 'numpy.float32' object does not support item assignment
```

Can we expand the test fixtures here to have both stereo and mono examples?

**Comment by tkell** [comment]
+1 to stereo and mono, yep.  

I'll probably have to retool synthesize to deal with mono, but I can do that.

If you input a mono file, do you get a mono file out?

**Comment by tkell** [comment]
Going to merge this (as it does fix the issue with stereo files), and then create a new branch and bug for the mono issue!

**Pull request merged**
