### PR TITLE
Simplifying and accelerating resample

### PR DESCRIPTION
**Pull request by bmcfee**
This is a tiny cleanup to more efficiently handle resampling on load.

Assuming tests still pass, this should be mergable.

### CODE REVIEW

**Comment by bmcfee** [comment]
Question @tkell:  is there any reason why we wouldn't pre-emptively downmix `analysis_samples` to mono?  From what I see, all the analyses first convert to mono anyway, and the zero-indexing is done on the raw sample data (kept in stereo or mono as specified).

**Comment by tkell** [comment]
@bmcfee, I think going to mono for the analysis is correct.  I recall that I did the verbose stuff that you want to raplce because librosa's resample function only took mono files.  Has that changed, or?

**Comment by bmcfee** [comment]
> I recall that I did the verbose stuff that you want to raplce because librosa's resample function only took mono files.

Ah, right, that was a relatively recent change.  It's in 0.4.2 though (relevant [PR](https://github.com/bmcfee/librosa/pull/288)).

**Comment by bmcfee** [comment]
redundant with #59

**Pull request closed without merging**
