### PR TITLE
updated travis scripts for new container environments

### LINKED ISSUE #16: Move to new Travis system
Tagging @bmcfee to do this, because he's done it for librosa.

### PR DESCRIPTION
**Pull request by bmcfee**
fixes #16

### CODE REVIEW

**Comment by bmcfee** [comment]
Also added coveralls integration, which we seemed to be missing before.

**Comment by bmcfee** [comment]
I think this is merge-ready.  Anyone else want to sign off?

**Comment by tkell** [comment]
I'll buy that for a dollar.  :fire_engine:

**Comment by bmcfee** [comment]
Merged. Please rebase the other outstanding PRs to get the coverage reports.

**Pull request merged**
