### PR TITLE
Move examples

### PR DESCRIPTION
**Pull request by tkell**

### CODE REVIEW

**Comment by tkell** [comment]
@bmcfee, I put the examples in data_files, not scripts, as I don't think we want reverse.py on the user's path.  Let me know if that is a bad idea.

**Comment by bmcfee** [comment]
Sounds good to me.

How do you feel about recoding the examples as ogg or flac?

Shipping wav files seems dirty to me.

**Comment by tkell** [comment]
I would prefer wav, because everyone can play it / everyone knows what it is and because it is a small pair of files.

**Comment by bmcfee** [comment]
Sure, if you feel strongly about it.  I'm a little curious who these remix coders are that don't know what an ogg is, but nbd.

**Pull request merged**
